### ISSUE TITLE
Exercise: movie suggestion

### ISSUE THREAD

**Issue by mlesniak** [micromata/webengineering-2017#1]
Hello,

please leave a comment under this issue.

**Comment by thedrayman** [comment]
Doctor Strange
I like all marvel movies, but this one is awesome! One of my favorite movie of the last year!

**Comment by CorvS** [comment]
Interstellar
Extraordinary movie in my opinion
Cheers

**Comment by PKolodzi** [comment]
+1 to Interstellar

**Comment by Albanos** [comment]
Inception --> sehr interessante und komplexe Story
Transformers 1 - n --> coole Effekte
Ey Mann wo ist mein Auto --> verpeilte story, zum abschalten :)

**Comment by adrian-sturm** [comment]
Mr Nobody 

Philosophie meets Science Fiction
Nachts um 3 zufällig reingeschaltet und bis zum Ende geblieben weil überaschend neu und interressant

**Comment by NecOnIce** [comment]
Shutter Island

Until today i still don't know what the truth was ...

**Comment by headcrab89** [comment]
Wild Tales – Jeder dreht mal durch!
Hab ich mal in der Sneak gesehen. Ist ein ziemlich verrückter Film über das Thema Ausrasten, ist aber ziemlich lustig :-)

**Comment by superjojo140** [comment]
Elling
Wenn man sich nimmt wie man ist, ist verrückt sein gar nicht mehr so komisch

**Comment by nikeee** [comment]
[Who Am I](http://www.imdb.com/title/tt3042408/); Because I think it's a great movie.

**Comment by CSchaub** [comment]
World of Warcraft
Meine Frau wollte unbedingt rein, spielt das Spiel auch schon lange. Ich war selten so positiv überrascht von einem Film, auf den ich weniger Bock hatte, spiele das Spiel nicht.

**Comment by hoechp** [comment]
+10 to Interstellar

**Comment by RalfHerzog** [comment]
Edge of Tomorrow; Looper; Triangle (2009)
Alle mit Zeitreisen

**Comment by Diana1024** [comment]
+11 to Interstellar

**Comment by Perdoci** [comment]
The Revenant because Leo won an Oscar for his performance in that Movie and everybody loves Leo :P

**Comment by yosefsaid** [comment]
Batman - The Dark Knight
Für mich der beste Superhelden Film
