### ISSUE TITLE
Frontend build system on Windows

### ISSUE THREAD

**Issue by thedrayman** [micromata/webengineering-2017#16]
Hi all,
perhaps, anyone cloud help me to get 'webpack' run on **Windows**. I spent two hours to get it running on Windows with no success. 
Adding the code from commit https://github.com/micromata/webengineering-2017/commit/164a0b4 to my project. Of course the `node ./node_modules/.bin/webpack` sh-script is not working on Windows so I changed this line to:
`"start": "node ./node_modules/.bin/webpack.cmd -w"`

But now I get this error after `npm start`:

```
E:\Entwicklung\web-engineering\webengineering-2017\src\main\frontend\node_modules\.bin\webpack.cmd:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

I also tried a minimum of code in the webpack.cmd but with the same results - `Invalid or unexpected token` or `Unexpected string`. 

So, any ideas what to do?

**Comment by mlesniak** [comment]
I'm just guessing, but as a hack you could try to install node/npm manually for the system and see if this helps.

**Comment by thedrayman** [comment]
I had installed node/npm for Windows from node.org. But I will try installing a newer version tomorrow.

**Comment by thedrayman** [comment]
I think, I fixed it with a stupid workaround. 
In `package.json` I call the .js file directly and not the `.bin/webpack.cmd` script.

So `"start": "node ./node_modules/webpack/bin/webpack.js"` is working and creating a `bundle.js`.
