### ISSUE TITLE
Probleme beim ändern der ressource location

### ISSUE THREAD

**Issue by Albanos** [micromata/webengineering-2017#17]
Hi!

Ich wollte unter windows 8.1 der pfad der ressources für das frontend gemäß Commit "Deliver static files using the default Spring MVC implementation" anpassen.
Leider half auch der Kommentar des Kollegen thedrayman bei mir nicht weiter. Ich wähle seine Konfiguration und bekomme folgenden Fehler:

`2017-06-17 14:50:41.066  WARN 14652 --- [nio-8080-exec-3] .w.s.m.s.DefaultHandlerExceptionResolver : Failed to bind request element: org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "index"`

Googlen liefert mir keine direkten Hinweise. Änderungen an dem Pfad bewirken nur, dass ich Fehler im Browser bekomme, die einfach nur aussagen: `No Message aviable`.

Kennt jemand das Problem oder hat jemand einen Tipp?

Beste Grüße an euch

**Comment by mlesniak** [comment]
Ich hab eine Idee, aber Quellcode ist immer hilfreicher. Kannst Du Deine Version irgendwo committen?

**Comment by Albanos** [comment]
Hi Michael!

Danke für die schnelle Antwort.
Habe eben einen etwas größeren Commit unter meinem repository:

https://github.com/Albanos/webengineering-2017/tree/LHbranch

durchgeführt. Aktuelle Version sollte nun dort zu sehen sein.

**Comment by mlesniak** [comment]
![image](https://user-images.githubusercontent.com/1467/27253527-8fe31704-5376-11e7-9d88-8950970ac9de.png)

Du hast einen Endpunkt `/` -- der mappt bei einem Aufruf auf `localhost:8080` die URL "index" auf den gemappten Long-Wert. Das geht natürlich nicht ;-)

Pass also den RequestPath an.

**Comment by Albanos** [comment]
Oh, danke dir Michael!

Habe das nun angepasst; ich bekomme zwar noch keine Page (status 404 sagt der Browser), aber die erste Fehlermeldung ist gefixt... :)
Danke dir

**Comment by mlesniak** [comment]
Hey,

probier mal noch einen `/` hinter den Pfad zu setzen ;-) Klappt es dann?

```
spring.resources.static-locations=file:./src/main/frontend/
```

**Comment by Albanos** [comment]
Hi,

"haben Sie die Datei schonmal gelöscht und neu generiert?" :-)

Einfach die Datei nochmal neu eingebunden, auch den `/` an den Pfad angefügt und nun geht es.

Danke Michael!
