### ISSUE TITLE
Exercise: What's your exercise repository?

### ISSUE THREAD

**Issue by mlesniak** [micromata/webengineering-2017#2]
Hi,

Write me the link to your exercise repository.

Cheers,
Michael

**Comment by CorvS** [comment]
https://github.com/CorvS/WebEng17

**Comment by adrian-sturm** [comment]
https://github.com/adrian-sturm/WebEngineering_SoSe17

**Comment by thedrayman** [comment]
https://github.com/thedrayman/webengineering-2017

**Comment by Albanos** [comment]
I have make a fork: https://github.com/Albanos/webengineering-2017

**Comment by NecOnIce** [comment]
git@github.com:NecOnIce/webengineering2017.git

**Comment by superjojo140** [comment]
https://github.com/superjojo140/webengineering-2017

**Comment by nikeee** [comment]
I gave you access to a private repository located here:
https://github.com/nikeee/uni-17ss-web-engineering-exercises

**Comment by RalfHerzog** [comment]
https://github.com/RalfHerzog/webengineering-2017

**Comment by KrazyJO** [comment]
https://github.com/KrazyJO/WebEngeneering2017

**Comment by CSchaub** [comment]
https://github.com/CSchaub/webengineering2017

**Comment by Starwars63** [comment]
https://github.com/Starwars63/Hi-.git

**Comment by hoechp** [comment]
https://github.com/hoechp/webengineering-2017

I also have a Wiki where I highlight some of my solutions.

**Comment by Starwars63** [comment]
Hey
Your repository is empty .. I think you should fill it with a source code
And I've done the same .. I only changed the name



Sent from my iPad
On 30.04.2017, at 14:09, Philipp Kolodziej <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/hoechp/webengineering-2017

**Comment by BiggA94** [comment]
https://github.com/BiggA94/webengineering-ss17

**Comment by HTakam** [comment]
https://github.com/HTakam/WebEngineering_SoSe17

**Comment by headcrab89** [comment]
https://github.com/headcrab89/webengineering-2017

**Comment by Diana1024** [comment]
https://github.com/Diana1024/webengineering-2017

**Comment by Tuli0** [comment]
https://github.com/Tuli0/WebEngineering-2017-MH

**Comment by Perdoci** [comment]
https://github.com/Perdoci/WebEng17.git

**Comment by niclas2109** [comment]
https://github.com/niclas2109/webengineering2017

**Comment by Anunkas** [comment]
https://github.com/Anunkas/webengineering-2017

**Comment by mkspoell** [comment]
https://github.com/mkspoell/webEngineering
