### ISSUE TITLE
Exercise: Heroku deployment

### ISSUE THREAD

**Issue by mlesniak** [micromata/webengineering-2017#3]
Hi,

Post a link to your heroku deployment of your currently deployed application

**Comment by thedrayman** [comment]
https://hidden-scrubland-73018.herokuapp.com

**Comment by CorvS** [comment]
https://nameless-falls-23627.herokuapp.com

**Comment by nikeee** [comment]
https://fast-ravine-26698.herokuapp.com

**Comment by RalfHerzog** [comment]
https://vast-ocean-16003.herokuapp.com/

**Comment by KrazyJO** [comment]
https://vast-bayou-93809.herokuapp.com/post

**Comment by CSchaub** [comment]
https://radiant-fjord-54679.herokuapp.com/

**Comment by superjojo140** [comment]
https://cryptic-brushlands-64783.herokuapp.com

**Comment by Starwars63** [comment]
https://vast-cove-89789.herokuapp.com

**Comment by hoechp** [comment]
https://sleepy-refuge-63511.herokuapp.com

**Comment by BiggA94** [comment]
https://webengineeringss17-bigga94.herokuapp.com

**Comment by CSchaub** [comment]
https://lit-woodland-37965.herokuapp.com/post

**Comment by Diana1024** [comment]
https://young-garden-55974.herokuapp.com/swagger-ui.html

**Comment by Tuli0** [comment]
https://webengineering-2017-mh.herokuapp.com

**Comment by NecOnIce** [comment]
https://vast-oasis-92068.herokuapp.com/

**Comment by mkspoell** [comment]
https://guarded-badlands-40503.herokuapp.com/

**Comment by headcrab89** [comment]
https://evening-castle-54501.herokuapp.com/
