### ISSUE TITLE
Serialisierung einer eigenen Klasse

### ISSUE THREAD

**Issue by superjojo140** [micromata/webengineering-2017#4]
Ich habe wie in der Aufgabe gefordert für die Posts einen eigene Klasse angelegt.
Wenn ich nun in Postman alle Posts abfrage bekomme ich folgende Fehlermeldung:

> Could not write JSON document: No serializer found for class com.micromata.webengineering.demo.post.Post and no properties discovered to create BeanSerializer

Was muss ich machen, damit ein Objekt meiner eigenen Klasse serialisiert werden kann?

**Comment by mlesniak** [comment]
Hi,

das sollte eigentlich direkt funktionieren. Schreib doch bitte mal die relevanten Teile 

* Deiner Post-Klasse
* des Post-Controllers

hier rein.

**Comment by superjojo140** [comment]
Die Klasse Post sieht so aus:


```
public class Post {
    String title;
    String text;
    String date;

    public Post(String title, String text, String date){
        this.title = title;
        this.text = text;
        this.date = date;
    }

    public String toString(){
        return "{title : " + this.title + " , text : " + this.text + " , date : " + this.date + " }";
    }

```

Ich dachte vllt. bringt es etwas, wenn ich eine toString() Methode definiere, klappt aber nicht.

**Comment by mlesniak** [comment]
Die Klasse `Post` sieht gut aus. Was macht der Controller?

**Comment by superjojo140** [comment]
Und der PostController:

```
package com.micromata.webengineering.demo.post;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * HTTP endpoint for a post-related HTTP requests.
 */
@RestController
public class PostController {
    @Autowired
    private PostService postService;

    @RequestMapping("/post")
    public List<Post> getPostList() {
        return postService.getPosts();
    }

    @RequestMapping(value = "/post/add")
    public void addPost(@RequestParam("title") String title, @RequestParam("text") String text) {
        postService.addPost(title,text);
    }
}
```

**Comment by mlesniak** [comment]
Was passiert, wenn Du getter in `Post` hinzufügst?

**Comment by superjojo140** [comment]
Das wars!
Danke läuft jetzt einwandfrei.

**Comment by mlesniak** [comment]
Kleine Ergänzung: Google Suche nach 

> Could not write JSON document: No serializer found for class POJO

und erster Link liefert [die Lösung](https://stackoverflow.com/questions/8367312/serializing-with-jackson-json-getting-no-serializer-found) ;-)

> As already described, the default configuration of an ObjectMapper instance is to only access properties that are public fields or have public getters/setters.

**Comment by superjojo140** [comment]
Uuups, Sorry!
Da hab ich wohl schlecht gesucht. Ich hab mir mehrere Stackoverflow Posts angeschaut, die Spring-Dokumentation und allgemeine Artikel über Java-Serialisierung.
Und habs nicht gefunden.

**Comment by mlesniak** [comment]
Alles in Ordnung -- solche Hinweise dienen dazu, es in Zukunft besser zu machen :)
