### ISSUE TITLE
Feedback geben funktioniert nicht

### ISSUE THREAD

**Issue by RalfHerzog** [micromata/webengineering-2017#6]
Lustig das hier jetzt zu schreiben, aber das anonyme Feedback funktioniert leider nicht (für mich)

![screenshot_2017-05-11_20-45-21](https://cloud.githubusercontent.com/assets/4613549/25966349/0c93b1cc-368b-11e7-92ef-7d7a37b58b50.png)

**Comment by mlesniak** [comment]
Hallo,

Danke für die Info, ich bin heute ganztägig in einem Kundentermin und kümmere mich heute Abend darum.

- Michael

**Comment by mlesniak** [comment]
Hallo,

Sollte jetzt wieder gehen.

 - Michael
