### ISSUE TITLE
Wünsche zum Thema "Best practices in der echten Welt"?

### ISSUE THREAD

**Issue by mlesniak** [micromata/webengineering-2017#7]
Hallo,

welche Themen und Aspekte interessieren euch denn besonders? Diese würde ich peu á peu in dem Teil best practices am Anfang jeder Vorlesung beleuchten.

Im Zweifel erstmal antworten und nicht lange überlegen -- filtern ist mein Job ;-)

Michael

**Comment by CorvS** [comment]
Hey,
mich würde das Thema Sicherheit/Authentifizierung interessieren.
Wie sichert man die REST Endpunkte richtig ab? Vor allem in Hinblick auf die eingehenden Parameter (z.B. Validierung von E-mail und Passwort), sodass die Angriffspunkte (SQL-Injection?) minimiert werden? 
Wie handhabt man die Authentifizierung bei Seiten mit sensiblen Daten (wie Amazon)? Tokens/Session-Ids? Wann/Wie werden diese erstellt und erneuert?

Grüße
Corvin

**Comment by superjojo140** [comment]
+1 für Thema Sicherheit.👍

**Comment by hoechp** [comment]
Zur UI-Seite:
User Experience & Responsiveness

**Comment by mkspoell** [comment]
auch hier ein +1 für die Sicherheit 👍

**Comment by RalfHerzog** [comment]
Ich würde gerne Lösungsansätze zu langen Verarbeitungsschritten erfahren. Mir geht es insbesondere um das Verarbeiten von großen Datenmengen, lang laufenden Prozessen und einer asynchronen Automatisierungsengine wie bspw. Camunda.

Hier mal ein kleines Szenario:
Als Beispiel könnte ich mir eine Webseite vorstellen, die Download-Links (z.B. von einem Smartphone) entgegen nimmt und später mit dem Download beginnt. Eine Warteschlange/Queue ist also nötig. Dieser Download kann in einem von vielen Status sein. Nach erfolgreichem Download soll die Datei zur Archivierung auf einen separaten Host übertragen werden.

Dazu folgende Fragen:
- Wie bildet man die Status ordentlich ab (z.B. Queued, In Progress, Failed, Success)?
  - Wie sinnvoll ist hier eine Automatisierungsengine?
  - Falls keine Automatisierungsengine; wie würde man selbst eine "einfache" State-Machine schreiben? Gibt es gute Frameworks/Tools dafür?
- Wie sieht es mit dem speichern der Fehlerursache aus? Sind dort Fehlercodes als Nummer und/oder Text sinnvoll?
- Wie sollte ein externer Dienst auf die Daten meines eigenen Dienstes zugreifen?
  - Direkter Datenbankzugriff?
  - Ebenfalls per REST API? Ist es dann sinnvoll einen separaten Dienst nach "innen" (nur für den anderen Dienst und keine Benutzer zugänglich) zu haben?
  - Wie sollten große Dateien gespeichert werden? Sicher nicht als BLOB in der Datenbank selbst. Also vielleicht als Referenz auf Dateinamen in unserer Datenbank?
- Wie "triggert" man periodisch auftretende Aufgaben? Beispielsweise das Aufräumen einer Datenbank. Die Universalwerkzeuge von vielen *nix - Systemen ist Cron oder SystemD. Gibts da ebenfalls Frameworks?

Ich weiß, das sind viele Fragen. Jedoch muss man sich diese schon für ein solch einfaches Szenario stellen :-)

**Comment by RalfHerzog** [comment]
Internationalisierung im Frontend wäre auch noch sehr interessant

**Comment by mlesniak** [comment]
> Internationalisierung im Frontend wäre auch noch sehr interessant

Kommt :)

**Comment by RalfHerzog** [comment]
Zurzeit habe ich ein Problem mit REST und Skalierung (Docker Container). Wie kann man garantieren, dass immer nur genau ein Prozess eine bestimmte Zeile in einer Tabelle verarbeitet? Also wie geht man am besten mit Race Conditions unter Anwendung von REST um? GET, POST und PATCH eignen sich meines Erachtens nicht wirklich gut dazu
